# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'fyp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for fyp
  pod 'Alamofire'
  pod 'IQKeyboardManager'
  pod 'Kingfisher'

  target 'TANetworking' do
    pod 'Alamofire'
  end

end
